### PR TITLE
Add dark mode to status bar

### PR DESCRIPTION
**Pull request by reupen**
This:

- adds a dark mode to the status bar
- reworks much of the status bar layout logic
- replaces the status bar playlist lock icon with the 🔒 character

The status bar is, unfortunately, another control that has no native dark mode, and therefore some workarounds are used to get something acceptable working.

Note also that currently, the 🔒 character doesn't seem to work out of the box on Windows 7 (Segoe UI Symbol isn't linked to Segoe UI there, at least in the VM I'm using).

### CODE REVIEW

**Comment by marc2k3** [comment]
> (Segoe UI Symbol isn't linked to Segoe UI there, at least in the VM I'm using).

Amusingly (or not!) it does work when using DirectWrite.

image

I was disappointed to see it was still monochrome in Windows 8.1. I thought that was the minimum version required for colour fonts but it seems support is rather limited.

It needs Windows 10 to be properly coloured...

image

**Comment by reupen** [comment]
> Amusingly (or not!) it does work when using DirectWrite.

Now that's interesting. When I wrote that comment, I also tried editing the [GDI font linking registry key](https://docs.microsoft.com/en-us/globalization/input/font-technology#font-linking) but even that didn't work. (Perhaps it doesn't handle code points that are more than one code unit correctly 🤷‍♂️ )

Now there is [a long-standing issue about migrating to DirectWrite](https://github.com/reupen/columns_ui/issues/15), though I was minded to see if I can get Uniscribe to fall back to Segoe UI Symbol to fix that character (if it's easy).

> I was disappointed to see it was still monochrome in Windows 8.1. I thought that was the minimum version required for colour fonts but it seems support is rather limited.

Sounds like the problem is the font (Segoe UI Emoji) there.

**Comment by marc2k3** [comment]
Seems like this particular icon being monochrome in 8.1 (and earlier versions of 10) was deliberate. I found this reference which shows the history and it's different again in 11....

image

https://emojipedia.org/locked/

**Comment by reupen** [comment]
Hmm, that is a lot of change – not sure I'm keen on the Windows 11 one to be honest, looks like an odd shopping bag or something to me 🤷

**Comment by marc2k3** [comment]
And here it is...

image

Also see the white blobs in the bottom corners of your nice dark menu.  I guess that's the price to pay with 11 applying rounded corners to everything. /sad face 

Even more fun, notification area tooltips getting squeezed in to an insanely low maximum width...

image

**Comment by reupen** [comment]
> And here it is...

Ugh, that also looks like they've ruined the Segoe UI Symbol version (l mean it looks unrecognisable to me). I thought the emoji would be better and easier to maintain but I may have to go back to using an icon (which means creating one, or finding one with an appropriate licence, as the old one was a 16x16 bitmap...)

> Also see the white blobs in the bottom corners of your nice dark menu. I guess that's the price to pay with 11 applying rounded corners to everything. /sad face

Hmm, that's odd. My laptop doesn't seem to be doing it but I saw it in a VM for a little while (is now gone there as well). No idea why that would happen, but I'll have to investigate as the dark menu stuff is all undocumented...

Also noted that the Windows Explorer dark mode colours are different on Windows 11 (compared to Windows 10) so I'll probably need to do something about that too...

> Even more fun, notification area tooltips getting squeezed in to an insanely low maximum width...
> 
> image

Not just that, ampersands are completely messed up too... Needs to go into the Feedback Hub (if someone hasn't already reported it...)

**Pull request merged**
