### PR TITLE
Refresh playlist switcher preferences

### PR DESCRIPTION
**Pull request by reupen**

### CODE REVIEW

**Comment by marc2k3** [comment]
Bit of a glitch where you enter the title formatting. I guess it needs shifting down a pixel or 2...

untitled

**Comment by reupen** [comment]
Thanks. It might depend on your DPI settings; I'll check and fix it soon.

**Comment by reupen** [comment]
Apparently it looks completely different at 125% and 100% DPI. I'll probably have to revert the font change as otherwise the rest of the dialog will scale differently to the CUI prefs.

**Comment by marc2k3** [comment]
So you're the one using 125%? I thought your first post was implied I was using different DPI settings but I'm always using default!

**Comment by reupen** [comment]
Yes, I'm usually using 125%. It was meant to look more like this:

image

**Pull request merged**
